"""Type stubs for cync_controller.const module."""

import logging
from typing import Any
from zoneinfo import ZoneInfo

CYNC_ACCOUNT_LANGUAGE: str
CYNC_ACCOUNT_PASSWORD: str | None
CYNC_ACCOUNT_USERNAME: str | None
CYNC_API_BASE: str
CYNC_BASE_DIR: str
CYNC_BRIDGE_DEVICE_REGISTRY_CONF: dict[str, Any]
CYNC_BRIDGE_OBJ_ID: str
CYNC_CHUNK_SIZE: int
CYNC_CLOUD_AUTH_PATH: str
CYNC_CLOUD_DEBUG_LOGGING: bool
CYNC_CLOUD_DISABLE_SSL_VERIFY: bool
CYNC_CLOUD_FORWARD: bool
CYNC_CLOUD_PORT: int
CYNC_CLOUD_RELAY_ENABLED: bool
CYNC_CLOUD_SERVER: str
CYNC_CMD_BROADCASTS: int
CYNC_CONFIG_FILE_PATH: str
CYNC_CORP_ID: str
CYNC_DEBUG: bool
CYNC_EXPOSE_DEVICE_LIGHTS: bool
CYNC_HASS_BIRTH_MSG: str
CYNC_HASS_STATUS_TOPIC: str
CYNC_HASS_TOPIC: str
CYNC_HASS_WILL_MSG: str
CYNC_LOG_CORRELATION_ENABLED: bool
CYNC_LOG_FORMAT: str
CYNC_LOG_HUMAN_OUTPUT: str | None
CYNC_LOG_JSON_FILE: str | None
CYNC_LOG_NAME: str
CYNC_MANUFACTURER: str
CYNC_MAXK: int
CYNC_MAX_TCP_CONN: int
CYNC_MINK: int
CYNC_MQTT_CONN_DELAY: int
CYNC_MQTT_HOST: str
CYNC_MQTT_PASS: str | None
CYNC_MQTT_PORT: str
CYNC_MQTT_USER: str | None
CYNC_PERF_THRESHOLD_MS: int
CYNC_PERF_TRACKING: bool
CYNC_PORT: int
CYNC_RAW: bool
CYNC_SRV_HOST: str
CYNC_SRV_SSL_CERT: str
CYNC_SRV_SSL_KEY: str
CYNC_STATIC_DIR: str
CYNC_UUID_PATH: str
CYNC_TOPIC: str
CYNC_TCP_WHITELIST: list[str] | None
CYNC_VERSION: str
DATA_BOUNDARY: int
DEVICE_LWT_MSG: bytes
ENABLE_EXPORTER: bool
EXPORT_SRV_START_TASK_NAME: str
FACTORY_EFFECTS_BYTES: dict[str, tuple[int, int]]
FOREIGN_LOG_FORMATTER: logging.Formatter
INGRESS_PORT: int
LOCAL_TZ: ZoneInfo
LOG_FORMATTER: logging.Formatter
MQTT_CLIENT_START_TASK_NAME: str
NCYNC_START_TASK_NAME: str
ORIGIN_STRUCT: dict[str, str]
PERSISTENT_BASE_DIR: str
RAW_MSG: str
SRC_REPO_URL: str
TCP_BLACKHOLE_DELAY: float
YES_ANSWER: tuple[str, str, str, str, str, int, str, str]
