name: "CyncLAN Bridge"
version: "0.0.2b2"
slug: "cync-lan"
description: "Local controller for Cync/C by GE smart devices (DNS redirection required)"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
services:
  - "mqtt:need"
init: false
watchdog: tcp://[HOST]:[PORT:23779]
boot: auto
ports:
  23779/tcp: 23779
  23778/tcp: null
ports_description:
  23779/tcp: "TCP port for Cync device communication"
  23778/tcp: "Web interface for device export (ingress)"
ingress: true
ingress_port: 23778
# ingress_entry: static/index.html
panel_icon: mdi:lightbulb-variant
panel_title: "CyncLAN"

# can grab core-mosquitto creds using this method and bashio
# but it reduces rating points, easier to just configure it
# hassio_api: true
# hassio_role: manager
# homeassistant_api: true

#environment:
#  TEST_VAR_111: "test_value_111 from add-on config.yaml environment dict"

options:
  account_username: null
  account_password: null
  debug_log_level: false
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  mqtt_topic: "cync_lan_addon"
  tuning:
    tcp_whitelist: ""
    command_targets: 2
    max_clients: 8

schema:
  account_username: email
  account_password: password
  debug_log_level: bool
  mqtt_topic: str
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str?
  mqtt_pass: password?
  tuning:
    tcp_whitelist: str?
    command_targets: int(1,)
    max_clients: int(1,)

map:
  # FAIL TO START if 'addon_config' and/or 'homeassistant_config' are defined while 'config' is included.
  - type: homeassistant_config
    read_only: false

url: "https://github.com/jslamartina/hass-addons"
host_network: true

#image: "ghcr.io/jslamartina/hass-addons:{arch}-cync-lan"
