from pathlib import Path
from typing import Any

def read_json_logs(path: str | Path, marker: str | None = ...) -> list[dict[str, Any]]: ...
def restart_addon_and_wait(slug: str, *, timeout: float | None = ...) -> None: ...
def get_addon_config(slug: str) -> dict[str, Any]: ...
def update_addon_config(slug: str, updates: dict[str, Any]) -> None: ...
def apply_addon_preset(slug: str, preset: str) -> None: ...
def get_log_levels_from_json(path: str | Path) -> dict[str, Any]: ...
