from typing import Any

class RequestException(Exception): ...
class ConnectionError(RequestException): ...
class Timeout(RequestException): ...

class Response:
    status_code: int
    text: str

    def json(self) -> Any: ...
    def raise_for_status(self) -> None: ...

class Session:
    headers: dict[str, str]

    def get(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    def post(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    def put(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    def patch(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    def delete(self, url: str, *args: Any, **kwargs: Any) -> Response: ...

class _ExceptionsModule:
    RequestException: type[RequestException]
    ConnectionError: type[ConnectionError]
    Timeout: type[Timeout]

exceptions: _ExceptionsModule

def get(url: str, *args: Any, **kwargs: Any) -> Response: ...
def post(url: str, *args: Any, **kwargs: Any) -> Response: ...
def put(url: str, *args: Any, **kwargs: Any) -> Response: ...
def patch(url: str, *args: Any, **kwargs: Any) -> Response: ...
def delete(url: str, *args: Any, **kwargs: Any) -> Response: ...
