"""Typed stubs for httpx."""

from collections.abc import AsyncIterator, Awaitable
from typing import Any

class AsyncClient:
    """Async HTTP client."""

    def __init__(self, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> AsyncClient: ...
    async def __aexit__(self, *args: object) -> None: ...
    def stream(self, method: str, url: str, **kwargs: Any) -> Awaitable[Any]: ...

class Response:
    """HTTP response."""

    def raise_for_status(self) -> None: ...
    def aiter_lines(self) -> AsyncIterator[str]: ...
