"""Typed stubs for the subset of playwright.sync_api APIs used in this repo."""

from collections.abc import Callable
from re import Pattern
from typing import Any

class Locator:
    """Playwright locator."""

    def is_visible(self, timeout: int | None = ...) -> bool: ...
    def click(self, **kwargs: Any) -> None: ...
    def fill(self, value: str, **kwargs: Any) -> None: ...
    def evaluate(self, expression: str | Callable[..., Any], **kwargs: Any) -> Any: ...
    @property
    def first(self) -> Locator: ...

class FrameLocator:
    """Frame locator."""

    def frame_locator(self, selector: str) -> FrameLocator: ...
    def get_by_role(self, role: str, name: str, **kwargs: Any) -> Locator: ...
    def get_by_text(self, text: str | Pattern[str], **kwargs: Any) -> Locator: ...

class ExpectAssertions:
    """Playwright expect assertions."""

    def to_be_visible(self, timeout: int | None = ...) -> None: ...

class Page:
    """Playwright page."""

    @property
    def url(self) -> str: ...
    def goto(self, url: str, **kwargs: Any) -> Any: ...
    def reload(self, **kwargs: Any) -> None: ...
    def wait_for_load_state(self, state: str = ..., **kwargs: Any) -> None: ...
    def wait_for_timeout(self, timeout: float) -> None: ...
    def wait_for_selector(self, selector: str, **kwargs: Any) -> None: ...
    def wait_for_url(self, url: str | Pattern[str], **kwargs: Any) -> None: ...
    def get_by_role(
        self, role: str, name: str | Pattern[str], **kwargs: Any
    ) -> Locator: ...
    def get_by_text(
        self, text: str | Pattern[str], exact: bool = ..., **kwargs: Any
    ) -> Locator: ...
    def locator(self, selector: str) -> Locator: ...
    def frame_locator(self, selector: str) -> FrameLocator: ...
    def evaluate(self, expression: str | Callable[..., Any], **kwargs: Any) -> Any: ...

def expect(locator: Locator) -> ExpectAssertions: ...
