class EditContextValidator:
    def __init__(self, file_path: str) -> None: ...
    def validate_context(self, context: str, start_line: int | None = ...) -> tuple[bool, str]: ...
    def validate_with_context_lines(
        self,
        old_string: str,
        start_line: int,
        context_before: int = ...,
        context_after: int = ...,
    ) -> tuple[bool, str]: ...
    def byte_diff_report(self, old_string: str, file_extraction: str) -> str: ...

def main() -> int: ...
