build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.14-alpine3.22
  amd64: ghcr.io/home-assistant/amd64-base-python:3.14-alpine3.22
labels:
  org.opencontainers.image.title: "Cync Controler - Home Assistant Add-on"
  org.opencontainers.image.description: "Local MQTT controller for Cync devices. Independent project maintained at https://github.com/jslamartina/hass-addons (DNS redirection required)"
  org.opencontainers.image.source: "https://github.com/jslamartina/hass-addons"
  org.opencontainers.image.licenses: "MIT"
