name: "Cync Controller"
version: "0.0.4.8"
slug: "cync-controller"
description: "Local controller for Cync lighting (DNS redirection required)"
image: "ghcr.io/jslamartina/cync-controller"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
services:
  - "mqtt:need"
init: false
watchdog: tcp://[HOST]:[PORT:23779]
boot: auto
ports:
  23779/tcp: 23779
  23778/tcp: null
ports_description:
  23779/tcp: "TCP port for Cync device communication"
  23778/tcp: "Web interface for device export (ingress)"
ingress: true
ingress_port: 23778

panel_icon: mdi:lightbulb-variant
panel_title: "Cync Controller"

options:
  account_username: null
  account_password: null
  debug_log_level: true
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_user: null
  mqtt_pass: null
  mqtt_topic: "cync_controller_addon"
  tuning:
    tcp_whitelist: ""
    command_targets: 2
    max_clients: 8
  cloud_relay:
    enabled: false
    forward_to_cloud: true
    cloud_server: "35.196.85.236"
    cloud_port: 23779
    debug_packet_logging: false
    disable_ssl_verification: false

schema:
  account_username: email
  account_password: password
  debug_log_level: bool
  mqtt_topic: str
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str?
  mqtt_pass: password?
  tuning:
    tcp_whitelist: str?
    command_targets: int(1,)
    max_clients: int(1,)
  cloud_relay:
    enabled: bool
    forward_to_cloud: bool?
    cloud_server: str?
    cloud_port: port?
    debug_packet_logging: bool?
    disable_ssl_verification: bool?

map:
  - type: homeassistant_config
    read_only: false

url: "https://github.com/jslamartina/hass-addons"
host_network: true
