JSONDict = dict[str, object]
LogEntry = JSONDict

def get_supervisor_token() -> str: ...
def get_addon_config(addon_slug: str) -> JSONDict: ...
def update_addon_config(addon_slug: str, config: JSONDict) -> bool: ...
def update_debug_log_level(addon_slug: str, enabled: bool) -> bool: ...
def restart_addon(addon_slug: str) -> bool: ...
def restart_addon_and_wait(addon_slug: str, wait_seconds: int = ...) -> None: ...
def get_addon_status(addon_slug: str) -> JSONDict: ...
def read_json_logs(addon_slug: str, lines: int = ...) -> list[LogEntry]: ...
def get_log_levels_from_json(logs: list[LogEntry]) -> set[str]: ...
def count_log_levels(logs: list[LogEntry]) -> dict[str, int]: ...
def filter_logs_by_level(logs: list[LogEntry], level: str) -> list[LogEntry]: ...
def filter_logs_by_logger(logs: list[LogEntry], logger_name: str) -> list[LogEntry]: ...
def apply_addon_preset(preset_name: str, addon_slug: str = ...) -> bool: ...
def stop_addon(addon_slug: str) -> bool: ...
def start_addon(addon_slug: str) -> bool: ...
